title: Kafka Tutorials
baseurl: ""
url: "http://kafka-tutorials.confluent.io"

github_url: https://github.com/confluentinc/kafka-tutorials
contribute_url: https://github.com/confluentinc/kafka-tutorials/blob/master/CONTRIBUTING.md

twitter_username: confluentinc
github_username: confluentinc

markdown: kramdown

sass:
  load_paths:
    - assets/sass
    - node_modules

exclude:
  - node_modules/
  - docker/
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - package-lock.json
  - Makefile
  - harness_runner
  - LICENSE
  - CONTRIBUTING.md

ak_javadoc_version: 23
cp_version: v5.2.1
google_tag_manager_id: GTM-NBVX4Z

plugins:
  - jekyll-asciidoc

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=highlightjs
  