title: "Kafka Tutorials: Learn Kafka with End-to-End Code Examples"
description: "Find, learn, and contribute Apache Kafka tutorials with full code examples for real use cases. Learn Kafka from Confluent, the real-time event streaming experts."

url: "https://kafka-tutorials.confluent.io"

github_url: https://github.com/confluentinc/kafka-tutorials
contribute_url: https://github.com/confluentinc/kafka-tutorials/blob/master/CONTRIBUTING.md

twitter_username: confluentinc
github_username: confluentinc

markdown: kramdown

sass:
  load_paths:
    - assets/sass
    - node_modules

exclude:
  - node_modules/
  - docker/
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - package-lock.json
  - Makefile
  - harness_runner
  - LICENSE
  - CONTRIBUTING.md
  - templates/
  - gen_project.sh

ak_javadoc_version: 23
cp_version: v5.3.0
google_tag_manager_id: GTM-M58HDC6

plugins:
  - jekyll-asciidoc
  - jekyll-last-modified-at
