title: Kafka Recipes
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mdrogalis-64b49dab-1657-4914-a0d0-339eafd2328d.s3-website-us-west-2.amazonaws.com"
twitter_username: confluentinc
github_username: confluentinc

markdown: kramdown

sass:
  load_paths:
    - assets/sass
    - node_modules

exclude:
  - node_modules/
  - docker/
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - package-lock.json
  - Makefile
  - deploy-to-s3.sh
  - harness_runner

ak_javadoc_version: 22
cp_version: v5.2.1
google_tag_manager_id: GTM-NBVX4Z
